org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.14.22
fabric_version=0.84.2+1.20.1

# Project properties
archives_base_name=touhou_little_maid-lite
maven_group=com.github.tartaricacid
mod_version=1.20.1-0.1.7.1-lite

# Optional mod versions
jei_version=15.13.50.40
architectury_api_version=9.1.12
rei_version=12.1.734
cloth_config_version=11.1.118
emi_version=1.1.5+1.20.1
jei_version=15.2.0.28
iron_chests_version=1.6.523
carry_on_version=2.1.2.7
patchouli_version=1.20.1-84
accessories_version=1.0.0.45
